"""Initial migration with all models

Revision ID: dab74dcaefb6
Revises:
Create Date: 2025-07-19 17:04:59.225242

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dab74dcaefb6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create teams table first (referenced by players)
    op.create_table(
        "teams",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('teams_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("mlb_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("abbreviation", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("city", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("division", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("league", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("venue_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="teams_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_teams_mlb_id", "teams", ["mlb_id"], unique=False)
    op.create_index("ix_teams_id", "teams", ["id"], unique=False)

    # Now create players table (references teams)
    op.create_table(
        "players",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('players_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("mlb_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("position", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("bats", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("throws", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("birth_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("current_team_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["current_team_id"], ["teams.id"], name="players_current_team_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="players_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_players_mlb_id", "players", ["mlb_id"], unique=False)
    op.create_index("ix_players_id", "players", ["id"], unique=False)
    op.create_index(
        "idx_player_position_team",
        "players",
        ["position", "current_team_id"],
        unique=False,
    )
    op.create_index("idx_player_name", "players", ["last_name", "first_name"], unique=False)
    op.create_table(
        "games",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('games_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("mlb_game_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("home_team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("away_team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "game_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("scheduled_innings", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("home_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("away_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("winning_team_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("innings_played", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("attendance", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "weather_conditions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["away_team_id"], ["teams.id"], name="games_away_team_id_fkey"),
        sa.ForeignKeyConstraint(["home_team_id"], ["teams.id"], name="games_home_team_id_fkey"),
        sa.ForeignKeyConstraint(["winning_team_id"], ["teams.id"], name="games_winning_team_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="games_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_games_mlb_game_id", "games", ["mlb_game_id"], unique=False)
    op.create_index("ix_games_id", "games", ["id"], unique=False)
    op.create_index("ix_games_game_date", "games", ["game_date"], unique=False)
    op.create_index("idx_game_team_date", "games", ["home_team_id", "game_date"], unique=False)
    op.create_index("idx_game_status_date", "games", ["status", "game_date"], unique=False)
    op.create_index(
        "idx_game_date_teams",
        "games",
        ["game_date", "home_team_id", "away_team_id"],
        unique=False,
    )
    op.create_index("idx_game_away_date", "games", ["away_team_id", "game_date"], unique=False)
    op.create_table(
        "game_stats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hits", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("errors", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("left_on_base", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pitches_thrown", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("strikes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("balls", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name="game_stats_game_id_fkey"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name="game_stats_team_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="game_stats_pkey"),
        sa.UniqueConstraint("game_id", "team_id", name="uq_game_team_stats"),
    )
    op.create_index("ix_game_stats_id", "game_stats", ["id"], unique=False)
    op.create_index("idx_game_stats_game", "game_stats", ["game_id"], unique=False)
    op.create_table(
        "model_performance",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("model_version", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "evaluation_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "accuracy",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "precision",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "recall",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "f1_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "winner_prediction_accuracy",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "runs_prediction_mae",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("games_evaluated", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("training_data_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("feature_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="model_performance_pkey"),
    )
    op.create_index("ix_model_performance_id", "model_performance", ["id"], unique=False)
    op.create_index(
        "idx_model_perf_version_date",
        "model_performance",
        ["model_version", "evaluation_date"],
        unique=False,
    )
    op.create_table(
        "player_stats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("games_played", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("at_bats", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hits", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("doubles", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("triples", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("home_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("runs_batted_in", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("walks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("strikeouts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "batting_average",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "on_base_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "slugging_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "innings_pitched",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("earned_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "earned_run_average",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("wins", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("losses", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("saves", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("strikeouts_pitched", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("walks_allowed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], name="player_stats_player_id_fkey"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name="player_stats_team_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="player_stats_pkey"),
        sa.UniqueConstraint("player_id", "season", "team_id", name="uq_player_season_team"),
    )
    op.create_index("ix_player_stats_id", "player_stats", ["id"], unique=False)
    op.create_index("idx_player_stats_team", "player_stats", ["team_id", "season"], unique=False)
    op.create_index("idx_player_stats_season", "player_stats", ["season"], unique=False)

    # Create statistics tables
    op.create_table(
        "hitting_stats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("games_played", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("at_bats", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("plate_appearances", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hits", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("doubles", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("triples", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("home_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("runs_scored", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("runs_batted_in", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stolen_bases", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("caught_stealing", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("base_on_balls", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("strikeouts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hit_by_pitch", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("sacrifice_hits", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("sacrifice_flies", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ground_into_double_play", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("left_on_base", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "batting_average",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "on_base_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "slugging_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ops",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "babip",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("total_bases", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "at_bats_per_home_run",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stolen_base_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ground_outs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("air_outs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "ground_outs_to_airouts",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("number_of_pitches", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("intentional_walks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name="hitting_stats_team_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="hitting_stats_pkey"),
        sa.UniqueConstraint("team_id", "season", name="uq_team_season_hitting"),
    )
    op.create_index("ix_hitting_stats_id", "hitting_stats", ["id"], unique=False)
    op.create_index("idx_hitting_stats_season", "hitting_stats", ["season"], unique=False)

    op.create_table(
        "pitching_stats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("games_played", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("wins", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("losses", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("saves", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("save_opportunities", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("holds", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("blown_saves", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "innings_pitched",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("batters_faced", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hits_allowed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("runs_allowed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("earned_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("home_runs_allowed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("strikeouts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("base_on_balls", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("intentional_walks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hit_batsmen", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("wild_pitches", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("balks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("number_of_pitches", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("complete_games", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("shutouts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("games_started", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ground_outs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("air_outs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "earned_run_average",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "whip",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "strikeouts_per_nine",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "walks_per_nine",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "hits_per_nine",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "home_runs_per_nine",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "strikeout_to_walk_ratio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ground_outs_to_airouts",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "pitches_per_inning",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "batting_average_against",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("inherited_runners", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("inherited_runners_scored", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("quality_starts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name="pitching_stats_team_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="pitching_stats_pkey"),
        sa.UniqueConstraint("team_id", "season", name="uq_team_season_pitching"),
    )
    op.create_index("ix_pitching_stats_id", "pitching_stats", ["id"], unique=False)
    op.create_index("idx_pitching_stats_season", "pitching_stats", ["season"], unique=False)

    op.create_table(
        "fielding_stats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("games_played", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "innings_played",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("total_chances", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("putouts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("assists", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("errors", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("double_plays", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("triple_plays", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "fielding_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "defensive_efficiency_ratio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "range_factor_per_game",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "range_factor_per_nine",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("outfield_assists", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("passed_balls", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("wild_pitches", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stolen_bases_allowed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("caught_stealing", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pickoffs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name="fielding_stats_team_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="fielding_stats_pkey"),
        sa.UniqueConstraint("team_id", "season", name="uq_team_season_fielding"),
    )
    op.create_index("ix_fielding_stats_id", "fielding_stats", ["id"], unique=False)
    op.create_index("idx_fielding_stats_season", "fielding_stats", ["season"], unique=False)

    op.create_table(
        "catching_stats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("games_played", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "innings_played",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("passed_balls", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("wild_pitches", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stolen_bases_allowed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("caught_stealing", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pickoffs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "caught_stealing_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("catchers_interference", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name="catching_stats_team_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="catching_stats_pkey"),
        sa.UniqueConstraint("team_id", "season", name="uq_team_season_catching"),
    )
    op.create_index("ix_catching_stats_id", "catching_stats", ["id"], unique=False)
    op.create_index("idx_catching_stats_season", "catching_stats", ["season"], unique=False)

    op.create_table(
        "predictions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "prediction_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "home_win_probability",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "away_win_probability",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "over_under_runs",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_runs_prediction",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "detailed_predictions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("model_version", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "confidence_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "feature_importance",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "actual_result",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "prediction_accuracy",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name="predictions_game_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="predictions_pkey"),
    )
    op.create_index("ix_predictions_id", "predictions", ["id"], unique=False)
    op.create_index(
        "idx_prediction_model",
        "predictions",
        ["model_version", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_prediction_game_type",
        "predictions",
        ["game_id", "prediction_type"],
        unique=False,
    )
    op.create_index("idx_prediction_created", "predictions", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hitting_stats_season", table_name="hitting_stats")
    op.drop_index("ix_hitting_stats_id", table_name="hitting_stats")
    op.drop_table("hitting_stats")
    op.drop_index("idx_pitching_stats_season", table_name="pitching_stats")
    op.drop_index("ix_pitching_stats_id", table_name="pitching_stats")
    op.drop_table("pitching_stats")
    op.drop_index("idx_fielding_stats_season", table_name="fielding_stats")
    op.drop_index("ix_fielding_stats_id", table_name="fielding_stats")
    op.drop_table("fielding_stats")
    op.drop_index("idx_catching_stats_season", table_name="catching_stats")
    op.drop_index("ix_catching_stats_id", table_name="catching_stats")
    op.drop_table("catching_stats")
    op.drop_index("idx_prediction_created", table_name="predictions")
    op.drop_index("idx_prediction_game_type", table_name="predictions")
    op.drop_index("idx_prediction_model", table_name="predictions")
    op.drop_index("ix_predictions_id", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_teams_id", table_name="teams")
    op.drop_index("ix_teams_mlb_id", table_name="teams")
    op.drop_table("teams")
    op.drop_index("idx_player_stats_season", table_name="player_stats")
    op.drop_index("idx_player_stats_team", table_name="player_stats")
    op.drop_index("ix_player_stats_id", table_name="player_stats")
    op.drop_table("player_stats")
    op.drop_index("idx_model_perf_version_date", table_name="model_performance")
    op.drop_index("ix_model_performance_id", table_name="model_performance")
    op.drop_table("model_performance")
    op.drop_index("idx_game_stats_game", table_name="game_stats")
    op.drop_index("ix_game_stats_id", table_name="game_stats")
    op.drop_table("game_stats")
    op.drop_index("idx_game_away_date", table_name="games")
    op.drop_index("idx_game_date_teams", table_name="games")
    op.drop_index("idx_game_status_date", table_name="games")
    op.drop_index("idx_game_team_date", table_name="games")
    op.drop_index("ix_games_game_date", table_name="games")
    op.drop_index("ix_games_id", table_name="games")
    op.drop_index("ix_games_mlb_game_id", table_name="games")
    op.drop_table("games")
    op.drop_index("idx_player_name", table_name="players")
    op.drop_index("idx_player_position_team", table_name="players")
    op.drop_index("ix_players_id", table_name="players")
    op.drop_index("ix_players_mlb_id", table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
