from datetime import datetime
from unittest.mock import AsyncMock

import pytest

from application.use_cases.player_stats_ingestion_use_cases import (
    IngestPlayerSeasonStatsUseCase,
    IngestPlayerStatsHistoryUseCase,
)
from domain.entities.player import Player
from domain.entities.player_stats_records import PlayerStatsGroupRecord, PlayerStatsHistoryRecord
from domain.entities.team import Team


def build_player(*, current_team_id: int | None = 5, player_id: int | None = 7) -> Player:
    player = Player.create(
        mlb_id=660271,
        first_name="Shohei",
        last_name="Ohtani",
        position="DH",
        bats="L",
        throws="R",
        active=True,
        current_team_id=current_team_id,
    )
    player.id = player_id
    return player


def build_team() -> Team:
    team = Team.create(
        mlb_id=119,
        name="Los Angeles Dodgers",
        abbreviation="LAD",
        city="Los Angeles",
        division="National League West",
        league="National League",
    )
    team.id = 5
    return team


def stats_response(*splits: dict) -> dict:
    return {"stats_data": [{"splits": list(splits)}]}


def build_season_use_case(
    mock_player_repository: AsyncMock,
    mock_team_repository: AsyncMock,
    mock_player_stats_repository: AsyncMock,
    mock_cache: AsyncMock,
    mlb_api: AsyncMock | None = None,
) -> IngestPlayerSeasonStatsUseCase:
    return IngestPlayerSeasonStatsUseCase(
        mock_player_repository,
        mock_team_repository,
        mock_player_stats_repository,
        mlb_api or AsyncMock(),
        mock_cache,
    )


def build_history_use_case(
    mock_player_repository: AsyncMock,
    mock_team_repository: AsyncMock,
    mock_player_stats_repository: AsyncMock,
    mock_cache: AsyncMock,
    mlb_api: AsyncMock | None = None,
) -> IngestPlayerStatsHistoryUseCase:
    return IngestPlayerStatsHistoryUseCase(
        mock_player_repository,
        mock_team_repository,
        mock_player_stats_repository,
        mlb_api or AsyncMock(),
        mock_cache,
    )


def build_group_record(stat_group: str, season: int, team_id: int | None, metrics: dict) -> PlayerStatsGroupRecord:
    return PlayerStatsGroupRecord.create(
        player_id=7,
        team_id=team_id,
        season=season,
        game_type="R",
        stat_group=stat_group,
        metrics=metrics,
    )


def build_history_entity(
    stat_group: str,
    external_reference: str,
    event_date: datetime | None,
    *,
    stat_type: str | None = None,
) -> PlayerStatsHistoryRecord:
    return PlayerStatsHistoryRecord.create(
        player_id=7,
        team_id=11,
        season=2025,
        game_type="R",
        stat_group=stat_group,
        stat_type=stat_type or ("gameLog" if event_date is not None else "statSplits"),
        external_reference=external_reference,
        payload={"sample": True},
        event_date=event_date,
    )


NORMALIZE_AGGREGATE_CASES = [
    pytest.param(
        "hitting",
        {
            "gamesPlayed": "1",
            "atBats": "2",
            "plateAppearances": "3",
            "hits": "4",
            "doubles": "5",
            "triples": "6",
            "homeRuns": "7",
            "runs": "8",
            "rbi": "9",
            "stolenBases": "10",
            "caughtStealing": "11",
            "baseOnBalls": "12",
            "strikeOuts": "13",
            "hitByPitch": "14",
            "sacBunts": "15",
            "sacFlies": "16",
            "leftOnBase": "17",
            "intentionalWalks": "18",
            "totalBases": "19",
            "avg": "0.201",
            "obp": "0.202",
            "slg": "0.203",
            "ops": "0.204",
            "babip": "0.205",
            "atBatsPerHomeRun": "0.206",
            "stolenBasePercentage": "0.207",
        },
        {
            "games_played": 1,
            "at_bats": 2,
            "plate_appearances": 3,
            "hits": 4,
            "doubles": 5,
            "triples": 6,
            "home_runs": 7,
            "runs_scored": 8,
            "runs_batted_in": 9,
            "stolen_bases": 10,
            "caught_stealing": 11,
            "base_on_balls": 12,
            "strikeouts": 13,
            "hit_by_pitch": 14,
            "sacrifice_hits": 15,
            "sacrifice_flies": 16,
            "left_on_base": 17,
            "intentional_walks": 18,
            "total_bases": 19,
            "batting_average": 0.201,
            "on_base_percentage": 0.202,
            "slugging_percentage": 0.203,
            "ops": 0.204,
            "babip": 0.205,
            "at_bats_per_home_run": 0.206,
            "stolen_base_percentage": 0.207,
        },
        id="hitting",
    ),
    pytest.param(
        "pitching",
        {
            "gamesPlayed": "1",
            "gamesStarted": "2",
            "wins": "3",
            "losses": "4",
            "saves": "5",
            "saveOpportunities": "6",
            "holds": "7",
            "blownSaves": "8",
            "battersFaced": "9",
            "hits": "10",
            "runs": "11",
            "earnedRuns": "12",
            "homeRuns": "13",
            "strikeOuts": "14",
            "baseOnBalls": "15",
            "intentionalWalks": "16",
            "hitBatsmen": "17",
            "wildPitches": "18",
            "balks": "19",
            "numberOfPitches": "20",
            "completeGames": "21",
            "shutouts": "22",
            "outs": "23",
            "strikes": "24",
            "pickoffs": "25",
            "qualityStarts": "26",
            "inningsPitched": "27.1",
            "era": "1.201",
            "whip": "1.202",
            "strikeoutsPer9Inn": "1.203",
            "walksPer9Inn": "1.204",
            "hitsPer9Inn": "1.205",
            "homeRunsPer9": "1.206",
            "strikeoutWalkRatio": "1.207",
            "pitchesPerInning": "1.208",
            "avg": "1.209",
            "obp": "1.210",
            "slg": "1.211",
            "ops": "1.212",
            "strikePercentage": "1.213",
            "winPercentage": "1.214",
        },
        {
            "games_played": 1,
            "games_started": 2,
            "wins": 3,
            "losses": 4,
            "saves": 5,
            "save_opportunities": 6,
            "holds": 7,
            "blown_saves": 8,
            "batters_faced": 9,
            "hits_allowed": 10,
            "runs_allowed": 11,
            "earned_runs": 12,
            "home_runs_allowed": 13,
            "strikeouts": 14,
            "base_on_balls": 15,
            "intentional_walks": 16,
            "hit_batsmen": 17,
            "wild_pitches": 18,
            "balks": 19,
            "number_of_pitches": 20,
            "complete_games": 21,
            "shutouts": 22,
            "outs": 23,
            "strikes": 24,
            "pickoffs": 25,
            "quality_starts": 26,
            "innings_pitched": 27.1,
            "earned_run_average": 1.201,
            "whip": 1.202,
            "strikeouts_per_nine": 1.203,
            "walks_per_nine": 1.204,
            "hits_per_nine": 1.205,
            "home_runs_per_nine": 1.206,
            "strikeout_to_walk_ratio": 1.207,
            "pitches_per_inning": 1.208,
            "batting_average_against": 1.209,
            "on_base_percentage": 1.21,
            "slugging_percentage": 1.211,
            "ops": 1.212,
            "strike_percentage": 1.213,
            "win_percentage": 1.214,
        },
        id="pitching",
    ),
    pytest.param(
        "fielding",
        {
            "gamesPlayed": "1",
            "gamesStarted": "2",
            "chances": "3",
            "putOuts": "4",
            "assists": "5",
            "errors": "6",
            "throwingErrors": "7",
            "doublePlays": "8",
            "triplePlays": "9",
            "outfieldAssists": "10",
            "passedBall": "11",
            "wildPitches": "12",
            "stolenBases": "13",
            "caughtStealing": "14",
            "catchersInterference": "15",
            "pickoffs": "16",
            "innings": "17.1",
            "fielding": "0.301",
            "defensiveEfficiencyRatio": "0.302",
            "rangeFactorPerGame": "0.303",
            "rangeFactorPer9Inn": "0.304",
            "stolenBasePercentage": "0.305",
        },
        {
            "games_played": 1,
            "games_started": 2,
            "total_chances": 3,
            "putouts": 4,
            "assists": 5,
            "errors": 6,
            "throwing_errors": 7,
            "double_plays": 8,
            "triple_plays": 9,
            "outfield_assists": 10,
            "passed_balls": 11,
            "wild_pitches": 12,
            "stolen_bases_allowed": 13,
            "caught_stealing": 14,
            "catchers_interference": 15,
            "pickoffs": 16,
            "innings_played": 17.1,
            "fielding_percentage": 0.301,
            "defensive_efficiency_ratio": 0.302,
            "range_factor_per_game": 0.303,
            "range_factor_per_nine": 0.304,
            "stolen_base_percentage": 0.305,
        },
        id="fielding",
    ),
    pytest.param(
        "catching",
        {
            "gamesPlayed": "1",
            "gamesPitched": "2",
            "atBats": "3",
            "hits": "4",
            "runs": "5",
            "homeRuns": "6",
            "strikeOuts": "7",
            "baseOnBalls": "8",
            "intentionalWalks": "9",
            "hitByPitch": "10",
            "totalBases": "11",
            "sacBunts": "12",
            "sacFlies": "13",
            "passedBall": "14",
            "wildPitches": "15",
            "stolenBases": "16",
            "caughtStealing": "17",
            "pickoffs": "18",
            "pickoffAttempts": "19",
            "catchersInterference": "20",
            "earnedRuns": "21",
            "battersFaced": "22",
            "hitBatsmen": "23",
            "avg": "0.401",
            "obp": "0.402",
            "slg": "0.403",
            "ops": "0.404",
            "stolenBasePercentage": "0.405",
            "strikeoutWalkRatio": "0.406",
        },
        {
            "games_played": 1,
            "games_pitched": 2,
            "at_bats": 3,
            "hits": 4,
            "runs": 5,
            "home_runs": 6,
            "strikeouts": 7,
            "base_on_balls": 8,
            "intentional_walks": 9,
            "hit_by_pitch": 10,
            "total_bases": 11,
            "sacrifice_bunts": 12,
            "sacrifice_flies": 13,
            "passed_balls": 14,
            "wild_pitches": 15,
            "stolen_bases_allowed": 16,
            "caught_stealing": 17,
            "pickoffs": 18,
            "pickoff_attempts": 19,
            "catchers_interference": 20,
            "earned_runs": 21,
            "batters_faced": 22,
            "hit_batsmen": 23,
            "batting_average": 0.401,
            "on_base_percentage": 0.402,
            "slugging_percentage": 0.403,
            "ops": 0.404,
            "stolen_base_percentage": 0.405,
            "strikeout_walk_ratio": 0.406,
        },
        id="catching",
    ),
    pytest.param(
        "running",
        {
            "gamesPlayed": "1",
            "plateAppearances": "2",
            "stolenBases": "3",
            "caughtStealing": "4",
            "runs": "5",
            "baseOnBalls": "6",
            "opportunities": "7",
            "stolenBasePercentage": "0.501",
        },
        {
            "games_played": 1,
            "plate_appearances": 2,
            "stolen_bases": 3,
            "caught_stealing": 4,
            "runs": 5,
            "base_on_balls": 6,
            "opportunities": 7,
            "stolen_base_percentage": 0.501,
        },
        id="running",
    ),
]


AGGREGATE_METRICS_CASES = [
    pytest.param("hitting", "plate_appearances", "batting_average", 5, 0.225, id="hitting"),
    pytest.param("pitching", "innings_pitched", "earned_run_average", 5, 0.225, id="pitching"),
    pytest.param("fielding", "total_chances", "fielding_percentage", 5, 0.225, id="fielding"),
    pytest.param("catching", "games_played", "stolen_base_percentage", 8, 0.225, id="catching"),
    pytest.param("running", "opportunities", "stolen_base_percentage", 5, 0.225, id="running"),
]
